### PR TITLE
Update to Cadence v1.0.0-preview.35

### PR DESCRIPTION
**Pull request by turbolent**
## Description

Automatically update to:
- [onflow/cadence v1.0.0-preview.35](https://github.com/onflow/cadence/releases/tag/v1.0.0-preview.35)
- [onflow/flow-go-sdk v1.0.0-preview.37](https://github.com/onflow/flow-go-sdk/releases/tag/v1.0.0-preview.37)
- [onflow/flow-go 604590f19db9](https://github.com/onflow/flow-go/commit/604590f19db9)
- [onflow/flow-emulator v1.0.0-preview.33](https://github.com/onflow/flow-emulator/releases/tag/v1.0.0-preview.33)

## Summary by CodeRabbit

- **New Features**
  - Improved transaction hash computation by removing unnecessary error handling, leading to more streamlined and efficient code.

- **Refactor**
  - Simplified the assignment logic for transaction hashes across multiple functions and tests.

- **Tests**
  - Updated test functions to remove error checks for transaction hash assignments, making tests more concise.

### CODE REVIEW

**Comment by turbolent** [comment]
I tried to adjust the code to the API changes in flow-go / resolve the TODO in aa3c50443ce9f5ccdc365e8a183d82be6c288e64, but it looks like the direct call tests are failing.

**Comment by m-Peter** [comment]
> I tried to adjust the code to the API changes in flow-go / resolve the TODO in [aa3c504](https://github.com/onflow/flow-evm-gateway/commit/aa3c50443ce9f5ccdc365e8a183d82be6c288e64), but it looks like the direct call tests are failing.

Much thanks for the update :raised_hands: 

I have fixed the tests in https://github.com/onflow/flow-evm-gateway/pull/324/commits/85cbd6f9cc8cb55f1993f777d7fdd2ea745cecaa
The failures were expected, due to a breaking change in the DirectCall hash calculation. See https://github.com/onflow/flow-go/pull/6118

**Review by m-Peter — APPROVED** [review]
LGTM :100:

**Comment by turbolent** [comment]
Thank you @m-Peter!

**Pull request merged**
